name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.3
  gradient_progress_indicator: ^1.0.0+5
  logger: ^1.1.0
  surf_lint_rules: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
